/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuditLogsRouteImport } from './routes/audit-logs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MerchantSettingsRouteImport } from './routes/merchant-settings'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as RecoveryLabRouteImport } from './routes/recovery-lab'
import { Route as RecoveryPoliciesRouteImport } from './routes/recovery-policies'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as TeamApprovalsRouteImport } from './routes/team-approvals'
import { Route as TransactionsRouteImport } from './routes/transactions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogsRoute = AuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantSettingsRoute = MerchantSettingsRouteImport.update({
  id: '/merchant-settings',
  path: '/merchant-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryLabRoute = RecoveryLabRouteImport.update({
  id: '/recovery-lab',
  path: '/recovery-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryPoliciesRoute = RecoveryPoliciesRouteImport.update({
  id: '/recovery-policies',
  path: '/recovery-policies',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamApprovalsRoute = TeamApprovalsRouteImport.update({
  id: '/team-approvals',
  path: '/team-approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/analytics': typeof AnalyticsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/merchant-settings': typeof MerchantSettingsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/recovery-lab': typeof RecoveryLabRoute
  '/recovery-policies': typeof RecoveryPoliciesRoute
  '/register': typeof RegisterRoute
  '/team-approvals': typeof TeamApprovalsRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/analytics': typeof AnalyticsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/merchant-settings': typeof MerchantSettingsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/recovery-lab': typeof RecoveryLabRoute
  '/recovery-policies': typeof RecoveryPoliciesRoute
  '/register': typeof RegisterRoute
  '/team-approvals': typeof TeamApprovalsRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/analytics': typeof AnalyticsRoute
  '/audit-logs': typeof AuditLogsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/merchant-settings': typeof MerchantSettingsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/recovery-lab': typeof RecoveryLabRoute
  '/recovery-policies': typeof RecoveryPoliciesRoute
  '/register': typeof RegisterRoute
  '/team-approvals': typeof TeamApprovalsRoute
  '/transactions': typeof TransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/analytics'
    | '/audit-logs'
    | '/dashboard'
    | '/login'
    | '/merchant-settings'
    | '/opportunities'
    | '/recovery-lab'
    | '/recovery-policies'
    | '/register'
    | '/team-approvals'
    | '/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/analytics'
    | '/audit-logs'
    | '/dashboard'
    | '/login'
    | '/merchant-settings'
    | '/opportunities'
    | '/recovery-lab'
    | '/recovery-policies'
    | '/register'
    | '/team-approvals'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/analytics'
    | '/audit-logs'
    | '/dashboard'
    | '/login'
    | '/merchant-settings'
    | '/opportunities'
    | '/recovery-lab'
    | '/recovery-policies'
    | '/register'
    | '/team-approvals'
    | '/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditLogsRoute: typeof AuditLogsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MerchantSettingsRoute: typeof MerchantSettingsRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  RecoveryLabRoute: typeof RecoveryLabRoute
  RecoveryPoliciesRoute: typeof RecoveryPoliciesRoute
  RegisterRoute: typeof RegisterRoute
  TeamApprovalsRoute: typeof TeamApprovalsRoute
  TransactionsRoute: typeof TransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-logs': {
      id: '/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant-settings': {
      id: '/merchant-settings'
      path: '/merchant-settings'
      fullPath: '/merchant-settings'
      preLoaderRoute: typeof MerchantSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery-lab': {
      id: '/recovery-lab'
      path: '/recovery-lab'
      fullPath: '/recovery-lab'
      preLoaderRoute: typeof RecoveryLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery-policies': {
      id: '/recovery-policies'
      path: '/recovery-policies'
      fullPath: '/recovery-policies'
      preLoaderRoute: typeof RecoveryPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-approvals': {
      id: '/team-approvals'
      path: '/team-approvals'
      fullPath: '/team-approvals'
      preLoaderRoute: typeof TeamApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditLogsRoute: AuditLogsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MerchantSettingsRoute: MerchantSettingsRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  RecoveryLabRoute: RecoveryLabRoute,
  RecoveryPoliciesRoute: RecoveryPoliciesRoute,
  RegisterRoute: RegisterRoute,
  TeamApprovalsRoute: TeamApprovalsRoute,
  TransactionsRoute: TransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
